# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetModel',
        ),
    ]
