# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_form', '0002_delete_budgetmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
